🔨 Added Annotation Step
d3b-center/D3b-Pathogenicity-Preprocessing pull request #7
Opened 2024-02-08 15:47 UTC by migbro

## Description

Nearly complete updates (waiting on germline snv annot workflow update), but close enough to start a review. This PR:
 - Adds a script to clean up ClinVar vcf, see end of README
 - Adds a bcftools annotation step. README also describes how this works
 - Add the annotation tools repo as a git submodule
 - Update links

Fixes # https://github.com/d3b-center/bixu-tracker/issues/2283

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] [With ClinVar Input](https://cavatica.sbgenomics.com/u/d3b-bixu/d3b-diskin-pathogenicity-dev/tasks/ca5f4452-8b0f-47cd-a4ee-2a1a15d78ac3/)
- [ ] [No ClinVar Input](https://cavatica.sbgenomics.com/u/d3b-bixu/d3b-diskin-pathogenicity-dev/tasks/e1716164-7e4d-402d-a704-6827a25860e3/)

**Test Configuration**:
* Environment:
* Test files:

## Checklist:

- [ x My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [ ] I have committed any related changes to the PR

2024-02-08 19:53 UTC, migbro commented
Just added a test here: https://cavatica.sbgenomics.com/u/d3b-bixu/d3b-diskin-pathogenicity-dev/tasks/7016d1b4-c735-4a42-a6a6-a7b55ef7ee19/ related to a requested feature

2024-02-08 20:05 UTC, dmiller15 requested changes
First pass thoughts.

2024-02-08 20:05 UTC, dmiller15 commented on scripts/cleanup_clinvar.py
> +                    split_records(record, update_alts, output)
so I'm unsure if this is needed. BCFtools doesn't need the records to be decomposed. According to their documentation:
> When multiple ALT alleles are present in the annotation file (given as comma-separated list of alleles), at least one must match one of the alleles in the corresponding VCF record. Similarly, at least one alternate allele from a multi-allelic VCF record must be present in the annotation file.

2024-02-08 20:11 UTC, wongjessica93 commented on README.md
> + - `annotation_vcf`: hg38 chromosome-formatted vcf file with multi-allelics split. If provided bcftools will add annotation from the specified columns for each variant that matches
If provided, BCFtools will add annotation from the specified columns for each variant that matches

2024-02-08 20:22 UTC, wongjessica93 commented on README.md
> +Optionally, if you which to add (and in needed, overwrite) another annotation from a vcf file (likely ClinVar), a bcftools strip and annotate steps are provided. The input vcf will be processed and i
Optionally, if you wish to add (and overwrite if needed) another annotation from a vcf file (likely ClinVar), a BCFtools strip and annotate steps are provided. The input vcf will be processed and its result will appear as an additional output in the workflow.

2024-02-08 20:22 UTC, wongjessica93 commented on README.md
> + - `annotation_vcf`: hg38 chromosome-formatted vcf file with multi-allelics split. If provided bcftools will add annotation from the specified columns for each variant that matches
- `annotation_vcf`: hg38 chromosome-formatted vcf file with multi-allelics split. If provided, BCFtools will add annotation from the specified columns for each variant that matches

2024-02-08 20:22 UTC, wongjessica93 commented on README.md
> + For the publication, [ClinVar release 20231028](https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/archive_2.0/2023/clinvar_20231028.vcf.gz) was used. In order to be compatible with our hg38-aligne
For the publication, [ClinVar release 20231028](https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/archive_2.0/2023/clinvar_20231028.vcf.gz) was used. In order to be compatible with our hg38-aligned vcfs, we additionally downloaded the [variant summary]

2024-02-08 20:31 UTC, migbro commented on README.md
> +It is recommended to have first run the [Kids First Germline Annotation Workflow](https://github.com/kids-first/kf-annotation-tools/blob/v1.1.0/docs/GERMLINE_SNV_ANNOT_README.md) first.
Um, tough. I am thinking/hoping it's unlikely that for this workflow, future releases will impact it....and if it does, we should point to the new version and update this one

2024-02-08 20:33 UTC, migbro commented on README.md
> +Documentation for this can be found [here](https://github.com/d3b-center/D3b-autoPVS1/tree/v2.0.0#readme)
Nah. Master occasionally has a way of not being what you want

2024-02-09 14:44 UTC, dmiller15 approved these changes

2024-02-13 17:03 UTC, wongjessica93 approved these changes

2024-02-13 18:09 UTC, merged